# Generated by Django 2.0.1 on 2018-01-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('nickname', models.CharField(default='Anonymous', max_length=50)),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Score'),
        ),
    ]
