# Generated by Django 2.0.1 on 2018-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='statement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
