# Generated by Django 2.0.1 on 2018-01-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180113_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Score'),
        ),
    ]
